version: '3'
#MAINTAINER: max-30ru@mail.ru
services:
  db:
    image: postgres:12.2

    command: postgres -c 'max_connections=1000' -c 'shared_buffers=12800MB' -c 'effective_cache_size=38400MB' -c 'maintenance_work_mem=2GB' -c 'checkpoint_completion_target=0.9' -c 'wal_buffers=16MB' -c 'default_statistics_target=500' -c 'random_page_cost=4' -c 'effective_io_concurrency=2' -c 'work_mem=1092kB' -c 'min_wal_size=4GB' -c 'max_wal_size=16GB' -c 'max_worker_processes=12' -c 'max_parallel_workers_per_gather=6' -c 'max_parallel_workers=12' -c 'max_parallel_maintenance_workers=4'

    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_user: test

    volumes:
      - ./data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  #
  #
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
