version: '3.6'
#MAINTAINER: max-30ru@mail.ru
services:
  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_user: test

    volumes:
      - ./data/:/var/lib/postgresql/data/
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf.conf
      - ./init_script/:/docker-entrypoint-initdb.d/

    command: postgres -c config_file=/etc/postgresql/postgresql.conf.conf
    ports:
      - 5432:5432
